Произошла ошибка, почини её:
TypeError: Cannot destructure property 'basename' of 'import_react.useContext(...)' as it is null.
    at LinkWithRef (https://preview--remont-plus-app.poehali.dev/node_modules/.vite/deps/react-router-dom.js?v=61978868:4490:8)
    at renderWithHooks (https://preview--remont-plus-app.poehali.dev/node_modules/.vite/deps/react-dom-xUljToa_.js?v=61978868:9706:19)
    at updateForwardRef (https://preview--remont-plus-app.poehali.dev/node_modules/.vite/deps/react-dom-xUljToa_.js?v=61978868:12044:19)
    at beginWork (https://preview--remont-plus-app.poehali.dev/node_modules/.vite/deps/react-dom-xUljToa_.js?v=61978868:13230:13)
    at HTMLUnknownElement.callCallback$1 (https://preview--remont-plus-app.poehali.dev/node_modules/.vite/deps/react-dom-xUljToa_.js?v=61978868:3130:11)
    at Object.invokeGuardedCallbackDev (https://preview--remont-plus-app.poehali.dev/node_modules/.vite/deps/react-dom-xUljToa_.js?v=61978868:3150:14)
    at invokeGuardedCallback (https://preview--remont-plus-app.poehali.dev/node_modules/.vite/deps/react-dom-xUljToa_.js?v=61978868:3189:32)
    at beginWork$1 (https://preview--remont-plus-app.poehali.dev/node_modules/.vite/deps/react-dom-xUljToa_.js?v=61978868:16119:5)
    at performUnitOfWork (https://preview--remont-plus-app.poehali.dev/node_modules/.vite/deps/react-dom-xUljToa_.js?v=61978868:15694:12)
    at workLoopSync (https://preview--remont-plus-app.poehali.dev/node_modules/.vite/deps/react-dom-xUljToa_.js?v=61978868:15643:36)